default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  timeout: 5000
  username: postgres
  password:

development:
  <<: *default
  database: docker_rails_dev

test:
  <<: *default
  database: docker_rails_test

production:
  <<: *default
